version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  load-data:
    build: .
    depends_on:
      - rabbitmq
    command: ["dotnet", "LoadData.dll"]
    
  app:
    build: .
    depends_on:
      - rabbitmq
    command: ["dotnet", "WebCAP.dll"]